-- ========================================================
-- SMA LABSCHOOL UNESA 1 - SUPABASE DATABASE SCHEMA
-- Execute this script in your Supabase SQL Editor
-- ========================================================

-- 1. Create FAQs Table
CREATE TABLE IF NOT EXISTS public.smal_faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create News / Updates Table
CREATE TABLE IF NOT EXISTS public.smal_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  caption TEXT,
  hashtags TEXT,
  published_at TEXT,
  image_url TEXT,
  image_alt TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Inquiries / Contact Form Table
CREATE TABLE IF NOT EXISTS public.smal_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ========================================================

-- Enable RLS
ALTER TABLE public.smal_faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smal_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smal_inquiries ENABLE ROW LEVEL SECURITY;

-- Allow Public Read Access for FAQs and News Updates
DROP POLICY IF EXISTS "Allow public read access for faqs" ON public.smal_faqs;
CREATE POLICY "Allow public read access for faqs" ON public.smal_faqs
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access for updates" ON public.smal_updates;
CREATE POLICY "Allow public read access for updates" ON public.smal_updates
  FOR SELECT USING (true);

-- Allow Public Insert Access for Inquiries (Contact Form Submissions)
DROP POLICY IF EXISTS "Allow public insert access for inquiries" ON public.smal_inquiries;
CREATE POLICY "Allow public insert access for inquiries" ON public.smal_inquiries
  FOR INSERT WITH CHECK (true);

-- ========================================================
-- SAMPLE SEED DATA
-- ========================================================

INSERT INTO public.smal_faqs (question, answer) VALUES
('Bagaimana cara mendaftar di SMA Labschool Unesa 1?', 'Pendaftaran dapat dilakukan secara online melalui website resmi atau langsung datang ke bagian Pendaftaran Peserta Didik Baru (PPDB) di kampus SMA Labschool Unesa 1.'),
('Apa saja program keunggulan sekolah?', 'Kami menyediakan program pembelajaran berbasis digital, kurikulum internasional, bimbingan persiapan PTN unggulan, serta berbagai kegiatan ekstrakurikuler prestasi.'),
('Apakah tersedia fasilitas beasiswa?', 'Ya, SMA Labschool Unesa 1 menyediakan jalur beasiswa prestasi akademik, non-akademik, serta beasiswa bantuan pendidikan.');

INSERT INTO public.smal_updates (title, caption, hashtags, published_at, image_url, image_alt) VALUES
('Penerimaan Peserta Didik Baru (PPDB) T.A 2026/2027', 'Pendaftaran gelombang pertama telah dibuka! Segera daftarkan diri Anda dan bergabunglah bersama keluarga besar SMA Labschool Unesa 1.', '#PPDB2026 #SMALabschoolUnesa #PrestasiJuara', 'AUG 28, 2026', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=800&auto=format&fit=crop', 'PPDB SMA Labschool Unesa'),
('Prestasi Siswa di Olimpiade Sains Nasional', 'Selamat kepada tim sains SMA Labschool Unesa 1 yang berhasil meraih medali emas dalam OSN 2026.', '#OSN2026 #SiswaBerprestasi #LabschoolJuara', 'AUG 20, 2026', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=800&auto=format&fit=crop', 'Siswa Berprestasi');
